SIM:
    DESIGN_ID: "philadelphia"
    DOMA_STARTING_FUNDS: 2000000
    DOMA_P_RENT_SHARE: 0.1
    DOMA_P_RESERVES: 0.05
    DOMA_P_EXPENSES: 0.05
    DESIRABILITY_STRETCH_FACTOR: 72
    BASE_APPRECIATION: 1.02
    SAMPLE_SIZE: 10
    TENANT_SAMPLE_SIZE: 30
    TREND_MONTHS: 12
    RENT_INCREASE_RATE: 1.05
    MOVING_PENALTY: 10
PLAY:
    BURN_IN: 12
    TURN_SEQUENCE: [3, 10, 3, 100]
    MIN_STEP_DELAY: 10
    PAUSE_BETWEEN_RUNS: 20
